version: 2
	jobs:
		build:
		deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
        name: Deploy Master to Heroku
        command: |
        git push https://heroku:57a9a39a-d834-4675-8d2c-4e1a519c5783@git.heroku.com/deliver-it-well-ops-200.git master

  workflows:
    version: 2
    build-deploy:
      jobs:
        - build
        - deploy:
          requires:
          - build
          filters:
          branches:
            only: master
			# Download and cache dependencies
			- restore_cache:
				keys:
				- v1-dependencies-{{ checksum "package.json" }}
				# fallback to using the latest cache if no exact match is found
				- v1-dependencies-

			- run: yarn install

			- save_cache:
				paths:
				- node_modules
				key: v1-dependencies-{{ checksum "package.json" }}

			# run tests!
			- run: yarn test