version: 2
jobs:
  build:
    deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Deploy Master it pto Heroku
          command: |
            git push https://heroku:57a9a39a-d834-4675-8d2c-4e1a519c5783@git.heroku.com/deliver-it-well-ops-200.git main
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main